export enum CMD_TYPE {
  GENERIC_CHAT = -1,
  INVALID = 0,

  DESIGN_INTENTION = 1,
  CORE_COMPONENTS = 2,

  CURRENT_COMPONENT = 3,
  SIMILAR_COMPONENTS = 4,
  CHECK_SYMBOL_CONNECTIONS = 5,
  COMPONENT_PINS_DETAILS = 6,
  SYMBOL_UNCONNECTED_PINS = 7,
}

export type SYMBOL_CMD_TYPE =
  | CMD_TYPE.CURRENT_COMPONENT
  | CMD_TYPE.SIMILAR_COMPONENTS
  | CMD_TYPE.CHECK_SYMBOL_CONNECTIONS
  | CMD_TYPE.COMPONENT_PINS_DETAILS
  | CMD_TYPE.SYMBOL_UNCONNECTED_PINS;

export const READABLE_CMD = {
  [CMD_TYPE.DESIGN_INTENTION]: "设计意图",
  [CMD_TYPE.CORE_COMPONENTS]: "核心组件",
  [CMD_TYPE.CURRENT_COMPONENT]: "当前组件",
  [CMD_TYPE.SIMILAR_COMPONENTS]: "相似器件推荐",
  [CMD_TYPE.CHECK_SYMBOL_CONNECTIONS]: "连接关系检查",
  [CMD_TYPE.COMPONENT_PINS_DETAILS]: "引脚详情",
  [CMD_TYPE.SYMBOL_UNCONNECTED_PINS]: "未连接引脚检查",
};
